Public Class clsOrderTextFB
    Public Property datum As String = ""
    Public Property kontakt_text As String = ""
    Public Property pomembno As String = ""
    Public Property spremembe1 As String = ""
    Public Property spremembe2 As String = ""
    Public Property stanje As String = ""
    Public Property status As String = ""
    Public Property status_text_1 As String = ""
    Public Property status_text_11 As String = ""
    Public Property status_text_2 As String = ""
    Public Property status_text_21 As String = ""
    Public Property status_text_22 As String = ""
    Public Property status_text_3 As String = ""
    Public Property status_text_31 As String = ""
    Public Property status_text_32 As String = ""
    Public Property status_text_4 As String = ""
    Public Property status_text_41 As String = ""
    Public Property status_text_42 As String = ""
    Public Property status_text_5 As String = ""
    Public Property status_text_51 As String = ""
    Public Property status_text_511 As String = ""
    Public Property status_text_52 As String = ""
    Public Property status_text_521 As String = ""
    Public Property status_text_53 As String = ""
    Public Property status_text_531 As String = ""
    Public Property status_text_6 As String = ""
    Public Property status_text_61 As String = ""
    Public Property status_text_62 As String = ""

    Public Property zahvala As String = ""
End Class
